Repository HSU-MovPick/MovPick, pull requests merged in 2024-12, with the labels that each got.

#42 상영중인 영화 데이터 추가
  data/cinemaData.js
  pages/MapPage.jsx
Labels: enhancement, 😈 JiWoon

#45 ✨ ChatbotPage - 특정 영화 도출 시 페이지 이동 구현 & ChatbotPage 컴포넌트 분리
  entities/Chatbot/openai.js
  entities/Chatbot/ui/ChatInput.jsx
  entities/Chatbot/ui/ChatMessages.jsx
  pages/ChatbotChattingPage.jsx
Labels: :recycle: Refact, :sparkles: Feat, :umbrella: khyaejin

#46 맵 페이지 디자인 추가
  pages/MapPage.jsx
Labels: :rotating_light: Fix, 😈 JiWoon

#53 🚨 FootNavBar & StandardBackground css 수정
  assets/ticket.png
  entities/Chatbot/ui/ChatInput.jsx
  pages/EmotionRecommendResult.jsx
  shared/components/StandardBackground.jsx
Labels: :rotating_light: Fix, :umbrella: khyaejin

#55 ✨ FEAT. 영화 상세 조회 페이지에 하단바 추가
  pages/MovieDetail.jsx
Labels: :sparkles: Feat
